### ISSUE TITLE
Infinite load when running the app

### ISSUE THREAD

**Issue by batbyR** [ManuBernard/calculettecarbone#3]
Hello Manu!

When I try to run the app with `npm run serve`, my local app only displays an infinite loader.

![image](https://user-images.githubusercontent.com/13064661/68089005-ea252b80-fe64-11e9-83b2-82eb34fd5e14.png)

Do you know why ?

Thank you!

**Comment by ManuBernard** [comment]
Dear Romain !

I'am new to git and i'am surprise to discover your message :)
Indeed this project is yet not meant to be collaborative. Therefor, here is
how to make it work :

You need to add some parameter to the URL :
http://localhost:8080/player/?code=micmac#/

Please let me know if it helps, and if this project interests you, i would
be happy to exchange a little !

Kind regards,
Manu

**Comment by batbyR** [comment]
Thanks Manu ! It works like a charm 🎉 

I understand totally and I only want to help you make this repo more collaborative!

I talked with Clément last Friday, I would be glad to make a call with you this week.

If your are interested, I have opened two Pull Requests here : #1  and #2  

PS : I update my Pull request to reflect the need to add this code parameter

Bonne soirée,

Romain
